import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Squares from "@/components/Squares";
import { ThemeProvider } from "@/components/theme-provider";
import Navbar from "@/components/Navbar";

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Sujib Shrestha",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${outfit.variable} antialiased`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
   <div className="relative min-h-screen">
  {/* Background Squares */}
  <div className="absolute inset-0 -z-10">

           <Squares
                speed={0.15}
                squareSize={54}
                direction="diagonal"
              />
      </div>

  {/* Foreground content */}
  <div className="relative z-10">
    <Navbar />
    {children}
  </div>
</div>
</ThemeProvider>
      </body>
    </html>
  );
}
